name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Debug Directory
        run: |
          pwd
          ls -la
          cd frontend/hullchat && ls -la
          
      - name: Install Dependencies
        working-directory: frontend/hullchat
        run: npm install
      
      - name: Build
        working-directory: frontend/hullchat
        run: npm run build
        
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Pull Vercel Environment Information
        working-directory: frontend/hullchat
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        working-directory: frontend/hullchat
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        working-directory: frontend/hullchat
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}